### ISSUE TITLE
Allow to move objects across vertical layers

### ISSUE THREAD

**Issue by bromagosa** [krls-ca/Snap--Build-Your-Own-Blocks#17]
Maybe by using the `AvPag`, `RePag`, `Home` and `End` keys, like other SVG editors do?

**Comment by krls-ca** [comment]
OK. I will follow the following logic:
`PageUp`: Up shape one layer
`PageDown`: Down shape one layer
`Home`: Move shape to top layer. 
`End`:  Move shape to bottom layer.
