### ISSUE TITLE
implement containsPoint() for all shapes

### ISSUE THREAD

**Issue by bromagosa** [krls-ca/Snap--Build-Your-Own-Blocks#5]

**Comment by krls-ca** [comment]
Done:
- SVGRectangle
- SVGCircle
- SVGEllipse

To do:
- SVGLine
- SVGBrush

**Comment by bromagosa** [comment]
Detect if a line contains a point, with a threshold: 

http://stackoverflow.com/questions/11907947/how-to-check-if-a-point-lies-on-a-line-between-2-other-points

**Comment by krls-ca** [comment]
It's done.

Bibliography used: 
- http://stackoverflow.com/questions/11907947/how-to-check-if-a-point-lies-on-a-line-between-2-other-points
- http://mathforum.org/library/drmath/view/63045.html
